version: '3'

services:
  ### PHP-FPM ##############################################
  laravel:
    build:
      context: ./
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ./:/srv/api/laravel
      - ../../packages/laravel:/srv/packages/laravel
    depends_on:
      - mysql

  ### NGINX Server #########################################
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/srv/api/laravel
      - ../demo/dist:/srv/api/admin
    ports:
      - "${NGINX_HTTP_PORT}:80"
    depends_on:
      - laravel

  ### MySQL ################################################
  mysql:
    build:
      context: ./docker/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}

  ### phpMyAdmin ###########################################
  phpmyadmin:
    build:
      context: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=pma
      - MYSQL_PASSWORD=pmapass
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mysql

  ### Redis ################################################
  redis:
    build:
      context: ./docker/redis
